Issue #750: fixed NoMethodError accessing node["monitoring"]["configs"]
- NoMethodError: undefined method `[]' for nil:NilClass recipes/default.rb:100
- http://stackoverflow.com/questions/19290710/ruby-syntax-in-chef-recipe

(cherry picked from commit 79e11e2e23f218af5570bef32d2d93769414f73c)